from abc import ABC, abstractmethod

class BaseGenerator(ABC):
    @abstractmethod
    def generate_round1(self, brief, checks, attachments):
        pass
    
    @abstractmethod
    def generate_round2(self, brief, checks, attachments, existing_files):
        pass
    
    def create_readme(self, brief, setup_instructions, usage_instructions):
        return f"""# Project

## Description
{brief}

## Setup
{setup_instructions}

## Usage
{usage_instructions}

## Code Explanation
This project was auto-generated based on the provided requirements.

## Files Included
- `index.html` - Main web page
- `script.js` - JavaScript functionality  
- `LICENSE` - MIT License
- `README.md` - This documentation

## License
MIT License - See LICENSE file for details.

---

*Auto-generated by LLM Deployment System*
"""